name: Deploy BAU Admin

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Zip artifact
              run: zip -r bau-admin.zip .

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Upload ZIP to S3
              run: aws s3 cp bau-admin.zip s3://business-as-usual-deployments/bau-admin.zip

            - name: Trigger CodeDeploy
              run: |
                  aws deploy create-deployment \
                    --application-name BusinessAsUsual-Admin \
                    --deployment-group-name BAU-Admin-Group \
                    --s3-location bucket=business-as-usual-deployments,bundleType=zip,key=bau-admin.zip
